/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtocolosRouteImport } from './routes/protocolos'
import { Route as JornadaSlugRouteImport } from './routes/jornada.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolosRoute = ProtocolosRouteImport.update({
  id: '/protocolos',
  path: '/protocolos',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadaSlugRoute = JornadaSlugRouteImport.update({
  id: '/jornada/$slug',
  path: '/jornada/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/protocolos': typeof ProtocolosRoute
  '/jornada/$slug': typeof JornadaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/protocolos': typeof ProtocolosRoute
  '/jornada/$slug': typeof JornadaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/protocolos': typeof ProtocolosRoute
  '/jornada/$slug': typeof JornadaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/protocolos' | '/jornada/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/protocolos' | '/jornada/$slug'
  id: '__root__' | '/' | '/protocolos' | '/jornada/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtocolosRoute: typeof ProtocolosRoute
  JornadaSlugRoute: typeof JornadaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocolos': {
      id: '/protocolos'
      path: '/protocolos'
      fullPath: '/protocolos'
      preLoaderRoute: typeof ProtocolosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornada/$slug': {
      id: '/jornada/$slug'
      path: '/jornada/$slug'
      fullPath: '/jornada/$slug'
      preLoaderRoute: typeof JornadaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtocolosRoute: ProtocolosRoute,
  JornadaSlugRoute: JornadaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
